//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchProjector.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChurchProjector.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment:.
        /// </summary>
        public static string Alignment_Colon {
            get {
                return ResourceManager.GetString("Alignment_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top:.
        /// </summary>
        public static string AlwaysOnTop_Colon {
            get {
                return ResourceManager.GetString("AlwaysOnTop_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner message.
        /// </summary>
        public static string BannerMessage {
            get {
                return ResourceManager.GetString("BannerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner speed:.
        /// </summary>
        public static string BannerSpeed_Colon {
            get {
                return ResourceManager.GetString("BannerSpeed_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bannertext:.
        /// </summary>
        public static string BannerText_Colon {
            get {
                return ResourceManager.GetString("BannerText_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner text size:.
        /// </summary>
        public static string BannerTextSize_Colon {
            get {
                return ResourceManager.GetString("BannerTextSize_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible display.
        /// </summary>
        public static string BibleDisplay {
            get {
                return ResourceManager.GetString("BibleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible search.
        /// </summary>
        public static string BibleSearch {
            get {
                return ResourceManager.GetString("BibleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book:.
        /// </summary>
        public static string Book_Colon {
            get {
                return ResourceManager.GetString("Book_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language_Books:.
        /// </summary>
        public static string BookLang_Colon {
            get {
                return ResourceManager.GetString("BookLang_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter:.
        /// </summary>
        public static string Chapter_Colon {
            get {
                return ResourceManager.GetString("Chapter_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file path.
        /// </summary>
        public static string CopyFilePath {
            get {
                return ResourceManager.GetString("CopyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free bible translation may be downloaded here:.
        /// </summary>
        public static string DownloadBibleTranslation {
            get {
                return ResourceManager.GetString("DownloadBibleTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the newest Version:.
        /// </summary>
        public static string DownloadNewestVersion_Colon {
            get {
                return ResourceManager.GetString("DownloadNewestVersion_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address:.
        /// </summary>
        public static string Email_Colon {
            get {
                return ResourceManager.GetString("Email_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors have occurred..
        /// </summary>
        public static string ErrorsOccurred {
            get {
                return ResourceManager.GetString("ErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fontsize:.
        /// </summary>
        public static string FontSize_Colon {
            get {
                return ResourceManager.GetString("FontSize_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fontsize from-to:.
        /// </summary>
        public static string FontSize_FromTo_Colon {
            get {
                return ResourceManager.GetString("FontSize_FromTo_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For the search).
        /// </summary>
        public static string ForTheSearch {
            get {
                return ResourceManager.GetString("ForTheSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS (Images per Seconds).
        /// </summary>
        public static string Fps_Colon {
            get {
                return ResourceManager.GetString("Fps_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub:.
        /// </summary>
        public static string GitHub_Colon {
            get {
                return ResourceManager.GetString("GitHub_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        public static string HistoryClear {
            get {
                return ResourceManager.GetString("HistoryClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage:.
        /// </summary>
        public static string HomePage_Colon {
            get {
                return ResourceManager.GetString("HomePage_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string Id_Colon {
            get {
                return ResourceManager.GetString("Id_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the paths for the songs and Bibles.
        ///The paths can be edited later in the settings..
        /// </summary>
        public static string InitHelperText {
            get {
                return ResourceManager.GetString("InitHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize.
        /// </summary>
        public static string InitWindowTitle {
            get {
                return ResourceManager.GetString("InitWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant hide.
        /// </summary>
        public static string InstantHide {
            get {
                return ResourceManager.GetString("InstantHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Lang_Colon {
            get {
                return ResourceManager.GetString("Lang_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language count:.
        /// </summary>
        public static string LangCount_Colon {
            get {
                return ResourceManager.GetString("LangCount_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor:.
        /// </summary>
        public static string Monitor_Colon {
            get {
                return ResourceManager.GetString("Monitor_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New song.
        /// </summary>
        public static string NewSong {
            get {
                return ResourceManager.GetString("NewSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file path.
        /// </summary>
        public static string OpenFilePath {
            get {
                return ResourceManager.GetString("OpenFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open logs.
        /// </summary>
        public static string OpenLogs {
            get {
                return ResourceManager.GetString("OpenLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        public static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to bibles.
        /// </summary>
        public static string PathToBibles_Colon {
            get {
                return ResourceManager.GetString("PathToBibles_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to songs.
        /// </summary>
        public static string PathToSongs_Colon {
            get {
                return ResourceManager.GetString("PathToSongs_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint presentations cannot be displayed because PowerPoint is not installed..
        /// </summary>
        public static string PowerPointIsMissing {
            get {
                return ResourceManager.GetString("PowerPointIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No program found for displaying the file.
        ///.
        /// </summary>
        public static string ProgramNotFound {
            get {
                return ResourceManager.GetString("ProgramNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Restart required).
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as bible.
        /// </summary>
        public static string SameAsBible {
            get {
                return ResourceManager.GetString("SameAsBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Search_Colon {
            get {
                return ResourceManager.GetString("Search_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search bible position.
        /// </summary>
        public static string SearchBiblePosition {
            get {
                return ResourceManager.GetString("SearchBiblePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut:.
        /// </summary>
        public static string Shortcut_Colon {
            get {
                return ResourceManager.GetString("Shortcut_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow hide.
        /// </summary>
        public static string SlowHide {
            get {
                return ResourceManager.GetString("SlowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song display.
        /// </summary>
        public static string SongDisplay {
            get {
                return ResourceManager.GetString("SongDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song edit.
        /// </summary>
        public static string SongEdit {
            get {
                return ResourceManager.GetString("SongEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song quick search.
        /// </summary>
        public static string SongQuickSearch {
            get {
                return ResourceManager.GetString("SongQuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song search.
        /// </summary>
        public static string SongSearch {
            get {
                return ResourceManager.GetString("SongSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPB format.
        /// </summary>
        public static string SpbFormat {
            get {
                return ResourceManager.GetString("SpbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string Theme_Colon {
            get {
                return ResourceManager.GetString("Theme_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Title_Colon {
            get {
                return ResourceManager.GetString("Title_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation:.
        /// </summary>
        public static string Translation_Colon {
            get {
                return ResourceManager.GetString("Translation_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Translation.
        /// </summary>
        public static string Translation_First {
            get {
                return ResourceManager.GetString("Translation_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Translation.
        /// </summary>
        public static string Translation_Second {
            get {
                return ResourceManager.GetString("Translation_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Translation.
        /// </summary>
        public static string Translation_Third {
            get {
                return ResourceManager.GetString("Translation_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors for the translations:.
        /// </summary>
        public static string TranslationColor_Colon {
            get {
                return ResourceManager.GetString("TranslationColor_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to version {0} is available..
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse:.
        /// </summary>
        public static string Verse_Colon {
            get {
                return ResourceManager.GetString("Verse_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of verses:.
        /// </summary>
        public static string VerseOrder {
            get {
                return ResourceManager.GetString("VerseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versionen.
        /// </summary>
        public static string Versionen {
            get {
                return ResourceManager.GetString("Versionen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML format.
        /// </summary>
        public static string XmlFormat {
            get {
                return ResourceManager.GetString("XmlFormat", resourceCulture);
            }
        }
    }
}
