//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchProjector.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ChurchProjector.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        public static string SameAsBible {
            get {
                return ResourceManager.GetString("SameAsBible", resourceCulture);
            }
        }
        
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        public static string Translation_Colon {
            get {
                return ResourceManager.GetString("Translation_Colon", resourceCulture);
            }
        }
        
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        public static string Search_Colon {
            get {
                return ResourceManager.GetString("Search_Colon", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string SearchBiblePosition {
            get {
                return ResourceManager.GetString("SearchBiblePosition", resourceCulture);
            }
        }
        
        public static string Translation_First {
            get {
                return ResourceManager.GetString("Translation_First", resourceCulture);
            }
        }
        
        public static string Translation_Third {
            get {
                return ResourceManager.GetString("Translation_Third", resourceCulture);
            }
        }
        
        public static string Translation_Second {
            get {
                return ResourceManager.GetString("Translation_Second", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        public static string SongQuickSearch {
            get {
                return ResourceManager.GetString("SongQuickSearch", resourceCulture);
            }
        }
        
        public static string SongSearch {
            get {
                return ResourceManager.GetString("SongSearch", resourceCulture);
            }
        }
        
        public static string BibleSearch {
            get {
                return ResourceManager.GetString("BibleSearch", resourceCulture);
            }
        }
        
        public static string NewSong {
            get {
                return ResourceManager.GetString("NewSong", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string InstantHide {
            get {
                return ResourceManager.GetString("InstantHide", resourceCulture);
            }
        }
        
        public static string SlowHide {
            get {
                return ResourceManager.GetString("SlowHide", resourceCulture);
            }
        }
        
        public static string BannerMessage {
            get {
                return ResourceManager.GetString("BannerMessage", resourceCulture);
            }
        }
        
        public static string LogFolder_Colon {
            get {
                return ResourceManager.GetString("LogFolder_Colon", resourceCulture);
            }
        }
        
        public static string OpenLogs {
            get {
                return ResourceManager.GetString("OpenLogs", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        public static string PowerPointIsMissing {
            get {
                return ResourceManager.GetString("PowerPointIsMissing", resourceCulture);
            }
        }
        
        public static string PowerPointIsConnected {
            get {
                return ResourceManager.GetString("PowerPointIsConnected", resourceCulture);
            }
        }
        
        public static string BannerText_Colon {
            get {
                return ResourceManager.GetString("BannerText_Colon", resourceCulture);
            }
        }
        
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        public static string ProgramNotFound {
            get {
                return ResourceManager.GetString("ProgramNotFound", resourceCulture);
            }
        }
        
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        public static string CopyFilePath {
            get {
                return ResourceManager.GetString("CopyFilePath", resourceCulture);
            }
        }
        
        public static string OpenFilePath {
            get {
                return ResourceManager.GetString("OpenFilePath", resourceCulture);
            }
        }
        
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        public static string Shortcut_Colon {
            get {
                return ResourceManager.GetString("Shortcut_Colon", resourceCulture);
            }
        }
        
        public static string SongEdit {
            get {
                return ResourceManager.GetString("SongEdit", resourceCulture);
            }
        }
        
        public static string Title_Colon {
            get {
                return ResourceManager.GetString("Title_Colon", resourceCulture);
            }
        }
        
        public static string LangCount_Colon {
            get {
                return ResourceManager.GetString("LangCount_Colon", resourceCulture);
            }
        }
        
        public static string Id_Colon {
            get {
                return ResourceManager.GetString("Id_Colon", resourceCulture);
            }
        }
        
        public static string VerseOrder {
            get {
                return ResourceManager.GetString("VerseOrder", resourceCulture);
            }
        }
        
        public static string Verse_Colon {
            get {
                return ResourceManager.GetString("Verse_Colon", resourceCulture);
            }
        }
        
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        public static string Theme_Colon {
            get {
                return ResourceManager.GetString("Theme_Colon", resourceCulture);
            }
        }
        
        public static string Monitor_Colon {
            get {
                return ResourceManager.GetString("Monitor_Colon", resourceCulture);
            }
        }
        
        public static string AlwaysOnTop_Colon {
            get {
                return ResourceManager.GetString("AlwaysOnTop_Colon", resourceCulture);
            }
        }
        
        public static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        public static string PathToBibles_Colon {
            get {
                return ResourceManager.GetString("PathToBibles_Colon", resourceCulture);
            }
        }
        
        public static string PathToSongs_Colon {
            get {
                return ResourceManager.GetString("PathToSongs_Colon", resourceCulture);
            }
        }
        
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        public static string BannerTextSize_Colon {
            get {
                return ResourceManager.GetString("BannerTextSize_Colon", resourceCulture);
            }
        }
        
        public static string BannerSpeed_Colon {
            get {
                return ResourceManager.GetString("BannerSpeed_Colon", resourceCulture);
            }
        }
        
        public static string FontSize_Colon {
            get {
                return ResourceManager.GetString("FontSize_Colon", resourceCulture);
            }
        }
        
        public static string Fps_Colon {
            get {
                return ResourceManager.GetString("Fps_Colon", resourceCulture);
            }
        }
        
        public static string BookLang_Colon {
            get {
                return ResourceManager.GetString("BookLang_Colon", resourceCulture);
            }
        }
        
        public static string SongShowFirstLineOfNextSong_Colon {
            get {
                return ResourceManager.GetString("SongShowFirstLineOfNextSong_Colon", resourceCulture);
            }
        }
        
        public static string ForTheSearch {
            get {
                return ResourceManager.GetString("ForTheSearch", resourceCulture);
            }
        }
        
        public static string SongDisplay {
            get {
                return ResourceManager.GetString("SongDisplay", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string BibleDisplay {
            get {
                return ResourceManager.GetString("BibleDisplay", resourceCulture);
            }
        }
        
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        public static string Alignment_Colon {
            get {
                return ResourceManager.GetString("Alignment_Colon", resourceCulture);
            }
        }
        
        public static string FontSize_FromTo_Colon {
            get {
                return ResourceManager.GetString("FontSize_FromTo_Colon", resourceCulture);
            }
        }
        
        public static string TranslationColor_Colon {
            get {
                return ResourceManager.GetString("TranslationColor_Colon", resourceCulture);
            }
        }
        
        public static string HomePage_Colon {
            get {
                return ResourceManager.GetString("HomePage_Colon", resourceCulture);
            }
        }
        
        public static string GitHub_Colon {
            get {
                return ResourceManager.GetString("GitHub_Colon", resourceCulture);
            }
        }
        
        public static string DownloadNewestVersion_Colon {
            get {
                return ResourceManager.GetString("DownloadNewestVersion_Colon", resourceCulture);
            }
        }
        
        public static string Email_Colon {
            get {
                return ResourceManager.GetString("Email_Colon", resourceCulture);
            }
        }
        
        public static string Versionen {
            get {
                return ResourceManager.GetString("Versionen", resourceCulture);
            }
        }
        
        public static string SpbFormat {
            get {
                return ResourceManager.GetString("SpbFormat", resourceCulture);
            }
        }
        
        public static string XmlFormat {
            get {
                return ResourceManager.GetString("XmlFormat", resourceCulture);
            }
        }
        
        public static string DownloadBibleTranslation {
            get {
                return ResourceManager.GetString("DownloadBibleTranslation", resourceCulture);
            }
        }
        
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        public static string Lang_Colon {
            get {
                return ResourceManager.GetString("Lang_Colon", resourceCulture);
            }
        }
        
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        public static string HistoryClear {
            get {
                return ResourceManager.GetString("HistoryClear", resourceCulture);
            }
        }
        
        public static string InitWindowTitle {
            get {
                return ResourceManager.GetString("InitWindowTitle", resourceCulture);
            }
        }
        
        public static string InitHelperText {
            get {
                return ResourceManager.GetString("InitHelperText", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        public static string Book_Colon {
            get {
                return ResourceManager.GetString("Book_Colon", resourceCulture);
            }
        }
        
        public static string Chapter_Colon {
            get {
                return ResourceManager.GetString("Chapter_Colon", resourceCulture);
            }
        }
        
        public static string ShowClock_Colon {
            get {
                return ResourceManager.GetString("ShowClock_Colon", resourceCulture);
            }
        }
    }
}
